# ??? ??????????
spring.application.name=quizer_backend

# ????????? ??????????? ? PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/quizer_db
spring.datasource.username=postgres
spring.datasource.password=10-ty5
spring.datasource.driver-class-name=org.postgresql.Driver

# ????????? Hibernate (????-???????? ??????)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ???????????? ?????? ?????? ?????
spring.servlet.multipart.max-file-size=10MB
# ???????????? ?????? ????? ??????? (???? ?????? ?????????)
spring.servlet.multipart.max-request-size=10MB